name: 'Copy file'
description: 'Copy local files'
author: 'Ricardo Canastro'
inputs:
  doc:  # id of input
    description: 'Who to greet'
    required: true
    default: './'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.doc }}
