name: copy files
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build a docker action
        uses: nx-amiribenabdellah/docker-action@v1.16